name: AI Generator Workflow

# Trigger the workflow when pushing to main branch
on:
  push:
    branches:
      - main
  workflow_dispatch: # allows manual trigger

jobs:
  run-ai-generator:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout your repo
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2️⃣ Set up Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: npm install
        working-directory: backend

      # 4️⃣ Run your backend script safely
      - name: Run AI generator
        working-directory: backend
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }} # secure injection
        run: node server.js
