name: AI Generator Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-ai-generator:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install
        working-directory: backend

      - name: Run AI generator (actual test)
        working-directory: backend
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          node -e "
          import fetch from 'node-fetch';
          const apiKey = process.env.OPENAI_API_KEY;
          const response = await fetch('https://your-ai-image-api.com/generate', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json', 'Authorization': `Bearer ${apiKey}` },
            body: JSON.stringify({ prompt: 'skibidi veiny ahh rizz test', type: 'image' })
          });
          const data = await response.json();
          console.log('Test Generation Result:', data);
          "
